const materiasMurcia = {
    ei: [
        'Todas las áreas'
    ],
    ep1: [
        'Ciencias de la Naturaleza',
        'Ciencias Sociales',
        'Educación Artística',
        'Educación Física',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Lengua Asturiana y Literatura',
        'Cultura Asturiana',

    ],
    ep2: [
        'Ciencias de la Naturaleza',
        'Ciencias Sociales',
        'Educación Artística',
        'Educación Física',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Lengua Asturiana y Literatura',
        'Cultura Asturiana',
    ],
    ep3: [
        'Ciencias de la Naturaleza',
        'Ciencias Sociales',
        'Educación Artística',
        'Educación Física',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Lengua Asturiana y Literatura',
        'Cultura Asturiana',
    ],
    ep4: [
        'Ciencias de la Naturaleza',
        'Ciencias Sociales',
        'Educación Artística',
        'Educación Física',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Lengua Asturiana y Literatura',
        'Cultura Asturiana',
    ],
    ep5: [
        'Ciencias de la Naturaleza',
        'Ciencias Sociales',
        'Educación Artística',
        'Educación Física',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Lengua Asturiana y Literatura',
        'Cultura Asturiana',
    ],
    ep6: [
        'Ciencias de la Naturaleza',
        'Ciencias Sociales',
        'Educación Artística',
        'Educación Física',
        'Educación en Valores Cívicos y Éticos',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Lengua Asturiana y Literatura',
        'Cultura Asturiana',
    ],

    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
    ],
    eso2: [
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Física y Química",
        "Segunda Lengua Extranjera",
        "Educación en Valores Cívicos y Éticos"
    ],
    eso3: [
        "Biología y Geología",
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Física y Química",
        "Música",
        "Tecnología y Digitalización",
        "Artes Escénicas y Danza",
        "Comunicación Audiovisual",
        "Cultura Clásica",
        "Digitalización Creativa",
        "Emprendimiento Personal y Social",
        "La Constitución Española y la Unión Europea",
        "Segunda Lengua Extranjera",
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Segunda Lengua Extranjera",
        "Biología y Geología",
        "Economía y Emprendimiento",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Latín",
        "Música",
        "Digitalización",
        "Tecnología",
        "Creaciones Audiovisuales y Plásticas",
        "Creaciones Escénico-Musicales",
        "Educación Financiera y Consumo Responsable",
        "El Mundo Clásico: Lenguaje, Historia y Patrimonio",
        "Filosofía. Retórica y Argumentación",
        "Investigación Científica e Innovación Tecnológica"
    ],


    bach1: [
        'Anatomía Aplicada', 'Análisis Musical', 'Artes Escénicas', 'Biología, Geología y Ciencias Ambientales', 'Coro y Técnica Vocal', 'Cultura Audiovisual', 'Cultura Audiovisual', 'Dibujo Artístico ', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Economía', 'Economía, Emprendimiento y Actividad Empresarial', 'Educación Física', 'El Legado Clásico', 'Filosofía', 'Física y Química', 'Griego', 'Historia del Mundo Contemporáneo', 'Latín', 'Lengua Asturiana y Literatura', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lenguaje y Práctica Musical', 'Literatura Universal', 'Matemáticas', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Matemáticas Generales', 'Proyectos Artísticos', 'Segunda Lengua Extranjera', 'Tecnología e Ingeniería', 'Tecnologías Digitales Aplicadas', 'Volumen'
    ],
    bach2: [
        'Análisis Musical', 'Artes Escénicas', 'Biología', 'Ciencias Generales', 'Coro y Técnica Vocal', 'Dibujo Artístico', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Diseño', 'Empresa y Diseño de Modelos de Negocio', 'Fundamentos Artísticos', 'Física', 'Geografía', 'Geología y Ciencias Ambientales', 'Griego', 'Historia de España', 'Historia de la Filosofía', 'Historia de la Música y de la Danza', 'Historia del Arte', 'Latín', 'Lengua Asturiana y Literatura', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Literatura Dramática', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Movimientos Culturales y Artísticos', 'Psicología y sociedad', 'Química', 'Segunda Lengua Extranjera', 'Tecnología e Ingeniería', 'Tecnologías Digitales Aplicadas', 'Técnicas de Expresión Gráfico-plástica'
    ],
}